# Generated by Django 4.2.16 on 2024-10-27 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='pleasant_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit_tracker.habit', verbose_name='Приятная привычка'),
        ),
    ]
