# Generated by Django 4.2.16 on 2024-11-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_habit',
            field=models.TimeField(verbose_name='Время на выполнение'),
        ),
    ]
