# Generated by Django 4.2.16 on 2024-11-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='next_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующая отправка'),
        ),
    ]
