# Generated by Django 4.2.16 on 2024-11-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0003_habit_next_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='next_send',
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodical',
            field=models.IntegerField(verbose_name='Периодичность в днях'),
        ),
    ]
